language: node_js
node_js:
  - "8"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
script :
  - "npm run build"
  - "npm run doc"
  - "git add es doc"
  - "git commit -m 'auto build and doc by travis'"
  - "npm test"
after_script:
  - "npm run test-nyc"

cache:
  directories:
  - node_modules

deploy:
  provider: npm
  email: heifade@126.com
  api_key: c2baad22-063f-4162-a53b-af7d0b34f39b
  on:
    tags: true
    repo: heifade/mysql-i
